### PR TITLE
v3.2.3.x Beta for v3.3 Production

### PR DESCRIPTION
**Pull request by TonyGravagno**
This beta release is being submitted as a release candidate to replace the current master branch. More feedback is being requested from the field and I expect a couple more point-releases before moving to 3.3 Production. But this PR initiates the process of moving the code into the master repo which will ultimately be the production download location, and the source for subsequent forks and inquiries.

### CODE REVIEW

**Comment by walterhiggins** [comment]
This PR is simply too big (153 files - many of which _seem_ to be spacing/indentation/line-ending changes).

**Comment by TonyGravagno** [comment]
This is a working new version for the existing production release. Yes, it's huge. See the release notes for a complete list of all changes - MUCH more than just spacing changes. Each point-release/commit has been thoroughly documented.

**Comment by walterhiggins** [comment]
I'm not happy with global style changes - can they be removed? As a general rule I'd advise not mixing global style changes with other changes.

**Comment by TonyGravagno** [comment]
Closing this PR and starting a new series of small updates beginning with #346.

**Pull request closed without merging**
