### PR TITLE
Branch Working Zombie : PR01

### PR DESCRIPTION
**Pull request by TonyGravagno**
Because it had too many changes, I've reverted Bad Zombie back to a baseline, in a new branch called Working-Zombie. It now agrees with the Development branch. Be sure to view changes with ?w=1.

There are no substantive changes in this PR. This is just the first sync update to ensure subsequent PRs to Development from Working Zombie will show clean diffs. New PRs will be submitted on approval of each prior update. It will take a while to get through the changes but I'm sure this is a better approach than the one massive update.

1. For the files that show whitespace changes, I believe there is an odd LF/CRLF in one side or the other. I'll ensure this is consistent and standard.
1. Since I'm pulling to Development, I don't understand why the original version in the diff doesn't reflect the recent updates to Development. The changes to blocks.js, watcher.js, and drone/index.js are already in the source via recent merged PRs. So the diffs shown here are not real changes,
1. In summary, the only actual change here is my updated .gitignore file.

### CODE REVIEW

**Comment by TonyGravagno** [comment]
I was trying to avoid the mess of history seen here but a) it has no effect on the final result and b) it would be a huge pain to have to start a new branch with no history. It requires significant git voodoo and might require deleting my repo and starting from scratch. That won't happen.

**Comment by jonathanperret** [comment]
Well I’m a bit puzzled why you closed #345 which does disable Oracle JDK 7 on Travis (« JDK8 support » as you put it has been there for quite a while). If I may, this is how you avoid huge unmergeable PRs : by merging small changes as they come, instead of accumulating them.

**Comment by TonyGravagno** [comment]
The next PR is going to include support for JDK8. There's no reason to process a pull that's going to be invalidated in perhaps less than a week. Unless there are a number of PRs processed in this time, and it's important for Travis to flag bad updates in a development branch, I don't see anything wrong with ignoring it for a few days. I hope that makes sense.

**Comment by jonathanperret** [comment]
Let me first say I think it's great that you've been putting so much energy in ScriptCraft.

Then, I can think of a number of reasons to merge #345 instead of waiting to integrate it in a bigger PR with unrelated changes, but I won't fight for its inclusion and will let @walterhiggins be the judge of what to merge.

Regarding the "mess of history", again @walterhiggins will choose whether to merge those commits (I know I wouldn't, but hey), but in case it's any help, here's all the Git voodoo you'd need to create a branch containing the changes from this PR in a single commit:

```
$ git checkout -b clean-zombie walterhiggins/development # create new branch from walter's
$ git merge -n --squash working-zombie
$ git commit -m "Convert CRLF to LF in a couple files, ignore Netbeans stuff"
```

I heartily recommend trying out http://learngitbranching.js.org/ as an interactive tutorial for the very useful but not entirely intuitive operations Git offers to handle any kind of situation!

**Comment by TonyGravagno** [comment]
Sincere thanks for that. With 40 years of development under my belt, and new tools demanding daily attention, I haven't yet made time to study the nuances of git - but of course now it's a requirement. I will do as you suggest but at this point I fear I'm spending more time on these tools and protocol than coding.

> instead of waiting to integrate it in a bigger PR with unrelated changes,

Really, PR02 is just about the J8/Nashorn/1.12 update.

**Comment by walterhiggins** [comment]
There are whitespace changes I'm not comfortable with so I applied your .gitignore changes via https://github.com/walterhiggins/ScriptCraft/commit/3e7250ae7c28e611e5cc5bb4f2b33282ba578bff

**Comment by softwaremaverick** [comment]
Now that the changes are in the development branch does this mean there will soon be a new release made available soon? 

On 23 September 2017 12:58:42 GMT+01:00, Walter Higgins <notifications@github.com> wrote:
>There are whitespace changes I'm not comfortable with so I applied your
>.gitignore changes via
>https://github.com/walterhiggins/ScriptCraft/commit/3e7250ae7c28e611e5cc5bb4f2b33282ba578bff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/walterhiggins/ScriptCraft/pull/346#issuecomment-331629332

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TonyGravagno** [comment]
@softwaremaverick : As to "soon", there's no time frame. You can use Bad Zombie with MC1.12 until we get Development functional. Comments on the documentation would be very helpful.

**Pull request closed without merging**
