### PR TITLE
Blockly

### PR DESCRIPTION
**Pull request by vorburger**
Hello @walterhiggins, here is finally the PR for the Blockly stuff! Do you like? Will merge? Best, M.

### CODE REVIEW

**Comment by walterhiggins** [comment]
Hi @vorburger ,
This is a significantly large pull request which includes source code from other Open source modules. My gut feeling is this should probably be in it's own repository/project separate from ScriptCraft. 
I'm uncomfortable with the idea of including the nanohttpd source code and devoxx source code here.
If you want to maintain a separate project/repo for this, that would be good. I just don't think this should be part of scriptcraft's source repo.

Walter

**Comment by TechplexEngineer** [comment]
Is this what LearnToMod is based on?

**Comment by djMax** [comment]
I had built something along these lines as a standalone server and then have a simple command in ScriptCraft to just fetch the code from the server and eval it. Now of course that's a bit dangerous, but since it's done at the behest of the user, I felt like it wasn't so bad. But importantly, it would mean little to no changes to the ScriptCraft code to support this. I do think this is a super important step in using this for certain age groups. The current "REPL" is just too brittle for new users.

**Comment by walterhiggins** [comment]
Closing PR as it is 4 years old.

**Pull request closed without merging**
