### PR TITLE
Allow loading json using require()

### PR DESCRIPTION
**Pull request by MrVoltz**

### CODE REVIEW

**Comment by walterhiggins** [comment]
Hi @MrVoltz 
Can you provide a use-case for this?
Walter

**Comment by MrVoltz** [comment]
Native Node.js has support for loading jsons using require() and I'm used to it. In scripcraft, I use it to load some static configs.

**Comment by tiredoftry** [comment]
I looked at using JSON data as a storage for building level data taken from minecraft schematic files. 

This would allow storing a buildings actual block types rather than having to code it in the call.  

This would allow for building cities with a single loop to read and create the blocks rather than having to have a loop per building type.

**Comment by walterhiggins** [comment]
Thanks @MrVoltz @tiredoftry 
Merged.

**Comment by walterhiggins** [comment]
@MrVoltz There seems to be a problem with this code now. I'm getting an error at startup

 Error evaluating /home/walter/cm18/scriptcraft/lib/require.js, javax.script.ScriptException: <eval>:320:1 Expected ; but found )

**Comment by walterhiggins** [comment]
@MrVoltz I'm rolling back this change because it breaks at startup - tested in:
* CanaryMod - Linux
* SpigotMC - Linux
* SpigotMC - MacOS

**Pull request merged**
