### PR TITLE
Docker container

### PR DESCRIPTION
**Pull request by tclavier**

### CODE REVIEW

**Comment by walterhiggins** [comment]
Hey @tclavier ,
Thanks for this. I'm not familiar with Docker yet. Can you move the docker section of the readme to after the Additional Resources heading?

**Comment by tclavier** [comment]
Yes I can, but imho, Docker it's to run it and it can be near Install section :-D

**Comment by walterhiggins** [comment]
I'm not sure most younger/beginner programmers would be familiar with Docker.

**Comment by tclavier** [comment]
It's done, and TravisCI says "All is well" :-)

**Pull request merged**
